baseURL = "https://ritarock.github.io/"
languageCode = "ja-jp"
title = "MY MEMORANDUM"
paginate = "10"
theme = "mainroad"
canonifyurls = true
publishDir = "docs"
hasCJKLanguage = true

[Params]
post_meta = ["date", "categories", "translations"]
highlightColor = "#000000"

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
