baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MyDocs'
theme = 'smol'

# Header
[menu]
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 1
